apiVersion: v1
kind: Template
metadata:
  name: subscription-inventory-ui
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: subscription-inventory
    spec:
      envName: ${ENV_NAME}
      title: Subscription Inventory
      deploymentRepo: https://github.com/RedHatInsights/subscription-inventory-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/subscriptionInventory
      image: ${IMAGE}:${IMAGE_TAG}
      module:
        manifestLocation: '/apps/subscription-inventory/fed-mods.json'
        modules:
          - id: 'subscription-inventory'
            module: './RootApp'
            routes:
              - pathname: /insights/subscriptions/inventory

parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/subscription-inventory-ui
